name: Deploy on Main Repo

on:
  workflow_run:
    workflows: ["docker-build"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.repository == 'ChristianLouis/LeagueLedger' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Webhook
        run: |
          curl -X POST https://docker2.kuechenserver.org/api/stacks/webhooks/51be0503-45f0-4202-9511-621a7477e3bc
